### ISSUE TITLE
internal Server error when try to access Log in with google before compiled

### ISSUE THREAD

**Issue by AmarjotS82** [edgarcoime/quizard#27]
When I start the app and then go to local host the app loads while some backend is still compiling but I can click the sign up and then log in with google button after clicking that I get an internal server error but if I wait for everything to compile before logging works fine

UI:
![image](https://github.com/user-attachments/assets/23afc29e-9cec-4579-966f-a72c0d5a474d)

![image](https://github.com/user-attachments/assets/09da8a4c-c4e5-4ec5-a226-3bce82c61ed2)

Backend:
Error:
![image](https://github.com/user-attachments/assets/a3246505-f4a5-4c53-b23a-a6035867f7cf)

After refreshing page and working like normal:
![image](https://github.com/user-attachments/assets/a64cd8d3-b48d-4c40-a28c-e26a97915414)

**Comment by reotam5** [comment]
since this only happens in dev environment in the first few second of launch, ill mark it as not planned
